### ISSUE TITLE
Use consistent styles for buttons on `:hover`

### ISSUE THREAD

**Issue by cvan** [Pinecast/www#14]
1. Hover over the submit button on the form at https://pinecast.com/signup/
2. Notice the `cursor` is `default` and there is no `text-decoration: underline`
3. Sign in at https://pinecast.com/login
4. Load https://pinecast.com/dashboard/ and hover over the `a[class="btn"]` elements (also 
5. Notice the `cursor` is `pointer` and the default `text-decoration: underline`

Solution:

``` css
button { cursor: pointer; }
.btn { text-decoration: none; }
```
